### ISSUE TITLE
[FEATURE] support POA chain

### ISSUE THREAD

**Issue by suraneti** [etherspot/skandha#117]
**Is your feature request related to a problem? Please describe.**
I currently need to set `unsafeMode` option to bypass stake validation in order to run on POA chain.

**Describe the solution you'd like**
Skandha bundler should operate without the need for `unsafeMode` on the POA chain, I've tested it on Besu.

**Comment by arddluma** [comment]
> **Is your feature request related to a problem? Please describe.** I currently need to set `unsafeMode` option to bypass stake validation in order to run on POA chain.
> 
> **Describe the solution you'd like** Skandha bundler should operate without the need for `unsafeMode` on the POA chain, I've tested it on Besu.

Hey there,

Unfortenately Besu and Nethermind do not support custom debug JS tracing.  Only way is to run on unsafeMode for now.

Anyway, we will check what we can do about it!

**Comment by ch4r10t33r** [comment]
> **Is your feature request related to a problem? Please describe.** I currently need to set `unsafeMode` option to bypass stake validation in order to run on POA chain.
> 
> **Describe the solution you'd like** Skandha bundler should operate without the need for `unsafeMode` on the POA chain, I've tested it on Besu.

Thanks for reporting this.

As described by @arddluma, one of the requirements of ERC4337 is the need to perform javascript tracing on the received UserOps. This feature depends on the underlying support from RPC node. AFAIK, neither Besu nor Nethermind clients have support for custom javascript tracing. Is this something you can verify? If they support tracing, then you should be able to run skandha in safe mode.
