### ISSUE TITLE
[FEATURE] Multiple executors per bundler instance

### ISSUE THREAD

**Issue by ch4r10t33r** [etherspot/skandha#125]
**Is your feature request related to a problem? Please describe.**
Single executor per bundler instance is a bottleneck.

**Describe the solution you'd like**

Multiple executors linked to a single instance of a bundler to facilitate parallel processing of UserOps from local mempool.

**Comment by 0xSulpiride** [comment]
https://github.com/etherspot/skandha/pull/138
