### ISSUE TITLE
How to skandha bundler along with mumbai testnet?

### ISSUE THREAD

**Issue by Linux-Server** [etherspot/skandha#133]
Im using skandha and the default config doesn't mention, how to connect skandha with mumbai testnet

**Comment by 0xSulpiride** [comment]
Hi @Linux-Server ,

If you want to run your own bundler, the network config for Mumbai would look like this:

```json
{
  "networks": {
    "mumbai": {
      "entryPoints": [
        "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
      ],
      "relayer": "0xYOUR_PRIVATE_KEY",
      "beneficiary": "0x7072475dF8EB2F9A9C8e7640141f08632f14BC4C",
      "rpcEndpoint": "https://polygon-mumbai-bor.publicnode.com"
    }
  }
}
```

If you want to connect to our Mumbai bundler from prime-sdk, just create a new instance of SDK with Mumbai's chain id.

```js
  const primeSdk = new PrimeSdk({ privateKey: process.env.WALLET_PRIVATE_KEY }, { chainId: 80001, projectKey: 'public-prime-testnet-key' })
```

Here is the list of other chains that we support: https://etherspot.fyi/prime-sdk/chains-supported

**Comment by Linux-Server** [comment]
> Hi @Linux-Server ,
> 
> If you want to run your own bundler, the network config for Mumbai would look like this:
> 
> ```json
> {
>   "networks": {
>     "mumbai": {
>       "entryPoints": [
>         "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
>       ],
>       "relayer": "0xYOUR_PRIVATE_KEY",
>       "beneficiary": "0x7072475dF8EB2F9A9C8e7640141f08632f14BC4C",
>       "rpcEndpoint": "https://polygon-mumbai-bor.publicnode.com"
>     }
>   }
> }
> ```
> 
> If you want to connect to our Mumbai bundler from prime-sdk, just create a new instance of SDK with Mumbai's chain id.
> 
> ```js
>   const primeSdk = new PrimeSdk({ privateKey: process.env.WALLET_PRIVATE_KEY }, { chainId: 80001, projectKey: 'public-prime-testnet-key' })
> ```
> 
> Here is the list of other chains that we support: https://etherspot.fyi/prime-sdk/chains-supported

Is it possible to coonect the primesdk with my own bundler node?

**Comment by 0xSulpiride** [comment]
@Linux-Server 
Yes, use this way of creating the SDK instance
```js
const primeSdk = new PrimeSdk(
    { privateKey: process.env.WALLET_PRIVATE_KEY },
    {
      chainId: Number(process.env.CHAIN_ID),
      bundlerRpcUrl: process.env.RPC_PROVIDER_URL,
      rpcProviderUrl: process.env.RPC_PROVIDER_URL,
      projectKey: 'public-prime-testnet-key'
    }
  );
```

Also you need to run the bundler with `--redirectRpc` and `--unsafeMode` flags (if you're using the public rpc)

**Comment by Linux-Server** [comment]
> @Linux-Server Yes, use this way of creating the SDK instance
> 
> ```js
> const primeSdk = new PrimeSdk(
>     { privateKey: process.env.WALLET_PRIVATE_KEY },
>     {
>       chainId: Number(process.env.CHAIN_ID),
>       bundlerRpcUrl: process.env.RPC_PROVIDER_URL,
>       rpcProviderUrl: process.env.RPC_PROVIDER_URL,
>       projectKey: 'public-prime-testnet-key'
>     }
>   );
> ```
> 
> Also you need to run the bundler with `--redirectRpc` and `--unsafeMode` flags (if you're using a public Mumbai rpc provider)

Is both bundlerRpcUrl and rpcProviderUrl are same? @0xSulpiride

**Comment by Linux-Server** [comment]
> @Linux-Server Yes, use this way of creating the SDK instance
> 
> ```js
> const primeSdk = new PrimeSdk(
>     { privateKey: process.env.WALLET_PRIVATE_KEY },
>     {
>       chainId: Number(process.env.CHAIN_ID),
>       bundlerRpcUrl: process.env.RPC_PROVIDER_URL,
>       rpcProviderUrl: process.env.RPC_PROVIDER_URL,
>       projectKey: 'public-prime-testnet-key'
>     }
>   );
> ```
> 
> Also you need to run the bundler with `--redirectRpc` and `--unsafeMode` flags (if you're using a public Mumbai rpc provider)

How to pass --redirectRpc` and `--unsafeMode while starting a skandha with docker
tried like below, but doesn't work

`sudo docker run --mount type=bind,source="$(pwd)"/config.json,target=/usr/app/config.json,readonly -dp 14337:14337 etherspot/skandha standalone —unsafeMode —redirectRpc`

**Comment by 0xSulpiride** [comment]
@Linux-Server there should be two dashes, not one
`docker run --mount type=bind,source="$(pwd)"/config.json,target=/usr/app/config.json,readonly -dp 14337:14337 etherspot/skandha standalone --unsafeMode --redirectRpc`
