### ISSUE TITLE
Unable to call any bundler node path?

### ISSUE THREAD

**Issue by Linux-Server** [etherspot/skandha#135]
Im running skandha bundler node and 'im unable to call the post call just like the your hosted urls
This is my skandha bundler url :  `http://13.235.70.162:14337/`
This is your bundler url : ` https://mumbai-bundler.etherspot.io/`
When call get method both are working fine, when it comes to post call, its showing method not found
<img width="1440" alt="Screenshot 2023-12-11 at 2 31 29 PM" src="https://github.com/etherspot/skandha/assets/67502584/e6dbcc60-1bdd-488a-9cbd-cd21e32569ef">

**Comment by arddluma** [comment]
> Im running skandha bundler node and 'im unable to call and post call just like the your hosted urls This is my skandha bundler url : `http://13.235.70.162:14337/` This is your bundler url : ` https://mumbai-bundler.etherspot.io/` When call get method both are working fine, when it comes to post call, its showing method not found <img alt="Screenshot 2023-12-11 at 2 31 29 PM" width="1440" src="https://private-user-images.githubusercontent.com/67502584/289479806-e6dbcc60-1bdd-488a-9cbd-cd21e32569ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODU2NTksIm5iZiI6MTcwMjI4NTM1OSwicGF0aCI6Ii82NzUwMjU4NC8yODk0Nzk4MDYtZTZkYmNjNjAtMWJkZC00ODhhLTljYmQtY2QyMWUzMjU2OWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA5MDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMWFmNDQ5NWZhOTliZWM5OThiNmE2ZGM1OTExOTg3MTlmZmEwYzFmYzZjZjI3OGQ5YTQ3NzNiMThmMTk5NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9gN085cthJOa1y-V_pEV9O0jmQE_u0hV3DobCUUAgOU">

Hey,
in this case  you should add chain Id as path. So, for Mumbai it will be http://13.235.70.162:14337/80001
