### ISSUE TITLE
Method eth_call is not supported

### ISSUE THREAD

**Issue by willpiam** [etherspot/skandha#27]
Skandha seems to only support RPC calls directly related to ERC4337

**Comment by ch4r10t33r** [comment]
Thanks for reporting the issue @willpiam . Although, `eth_call` is not part of the bundler specification. It does make sense for the bundler to create a wrapper to the underlying execution layer RPC node. This will ensure that all bundlers can work with UserOps.js. We shall be adding support for this and let you know when its available.

**Comment by willpiam** [comment]
Great! Thank you!

**Comment by ch4r10t33r** [comment]
Fixed in release: https://github.com/etherspot/skandha/releases/tag/0.0.3
