### ISSUE TITLE
[BUG] Cannot Access Associated Slot of Sender In Validation

### ISSUE THREAD

**Issue by doublespending** [etherspot/skandha#65]
### Describe the bug

Return Error when userOp uses ERC-20 as gas token in Paymaster. When I used `alchemy` or `stackup` bundler, the case can pass.

Paymaster:  [0x07865c6e87b9f70255377e024ace6630c1eaa37f](https://goerli.etherscan.io/address/0x07865c6e87b9f70255377e024ace6630c1eaa37f)
GasToken: [0x49040d242126f709b32623704e78bbe0991e6992](https://goerli.etherscan.io/address/0x49040d242126f709b32623704e78bbe0991e6992)

I suppose that it is not enough to just find one`keccak` candidate: https://github.com/etherspot/skandha/blob/master/packages/executor/src/services/UserOpValidation.ts#L241

Ref other bundler implementations:
* https://github.com/eth-infinitism/bundler/blob/main/packages/bundler/src/parseScannerResult.ts#L249-L272
* https://github.com/stackup-wallet/stackup-bundler/blob/main/pkg/entrypoint/simulation/storageslots.go#L44-L54

Error:
`0x49040d242126f709b32623704e78bbe0991e6992` is the gas token address not a paymaster.
```
'{"jsonrpc":"2.0","id":44,"error":{"message":"unstaked paymaster entity 0x49040d242126f709b32623704e78bbe0991e6992 accessed slot","data":{"paymaster":"0x49040d242126f709b32623704e78bbe0991e6992"},"code":-32502}}'
```

### Expected behavior

Success

### Operating system

macOS

### Skandha version or commit hash

b6e9c68

**Comment by ch4r10t33r** [comment]
Thanks for reporting this issue @doublespending . We are presently trying to reproduce this locally. We shall keep you posted.
